# Generated by Django 3.0.3 on 2020-02-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.URLField(unique=True, verbose_name='url')),
                ('response_status', models.IntegerField(null=True, verbose_name='status')),
                ('check_interval', models.PositiveIntegerField(verbose_name='check interval')),
                ('is_paused', models.BooleanField(default=False, verbose_name='paused')),
            ],
        ),
    ]
