# Generated by Django 3.0.3 on 2020-02-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='check_interval',
            field=models.PositiveIntegerField(default=5, verbose_name='check interval'),
        ),
        migrations.AlterField(
            model_name='url',
            name='is_paused',
            field=models.BooleanField(default=False, verbose_name='paused?'),
        ),
        migrations.AlterField(
            model_name='url',
            name='text',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
